language: node_js
node_js:
- 10.16.2
install:
- npm install
cache: npm
script:
- npm test
services:
- neo4j
env:
- NEO_VERSION="2.1.2"
deploy:
  provider: heroku
  api_key:
    secure: DVdZ5A23bajPZeWHrPTCySk4Xmo5yzuI41wnmqGksnIm6Zjn0E+J4jBMvKnPiIGMcmyV/7hU19P2Sn9VFbdjfGVND4GdPHMWcmrs3qzn7yvTSV5o3Vu1+rCDNZBWLkLYPUOyT4V4n6MNgJ1x6GB19spfmVeoKjtm6akRfgQp283jG7dAX2c+GmOYl0jWS0AXqP828cPYdM1eU6h1clXUdsHuj7je0QaFXRIsCPcErL7iG3OiKxNI6+rrbRgtGJ2G8FpIVAGTY5YTAwmduA7jqBUrlgK0IeZ3spBBj/EgD3C1NWrXZbf/5ARYsF7XPWZcNY+2P/QpCrbprJP03mikB28GnGtXfYFMeIJcvAkzui5KJ5OOEihW1mNNSGqmpR56XWZHQV+7PwcmHsF2pQp7hHQBF2uj0qSlNgtA86niwC1VOAffIwUpt10CneQJ5NzpTFRo+RidzFlmkRnqNUuuLolhOTs9Z3A09t6QD3bAh9Hs+oShqoSCgYReFvxWLhPwpJmwjW3Gd288DlwFHNqYTpHfSfQhGBzNxYIl0aOYgtM+JmYDLXmOY8qKTnsh0VJkDk7IexRkpDD3NV/apx6rH4GfzKP+/WP23YUBDi6/Y8GqyvbpQSBU7jKddz/jy6MHqph8ysyupwURq+oAPwP9iyS2IX5+iu5iQUoUFPHvSGI=
  strategy: git
