language: node_js
node_js:
- 10.16.2
install:
- npm install
cache: npm
script:
- npm test
services:
- neo4j
env:
- NEO_VERSION="2.1.2"
deploy:
  provider: heroku
  api_key:
    secure: IPQIqh0Y60Yy8WUlkv4as6qLb2XIjLoOh+3EatODyPQwlfL+ChQvKGZLRzKKwdOUIDK2fsw+6MbuJyjEDoqhktODc/O21m5ulZQ/tKNjPeiYb8zhqjH2ntwkHyE9zixy84WmFm0hV9NbNGx2bdEOc14CEXKnF/ChvxelA4f9XfZJ0UmqHbenIdiLmidoqUdO5NZKuKz+xC9DATVUO0xeY/hlQ0ssenoELRQTki6y5URMpYfGROVxv4eckGsZs8lLEZtFNlhd8Hk9DJ2WZCqQtFdTI/cWVpDCKcPWvjzRgjXi6ybkMAUICWS6omULDSfaeTkwjuFRbBXa57Knn8Tu2bOaS15GNWf1BUo4N4y2kLl5p3EJQ1ONQtuZBQM/koDNWFA9bk4MUr14tDqbph2AgEjsLJKIDvjAK/yZYt4Noue5By27C9PQfYsXvukd9AHBhb+eH2DnuGK1OwQiMBf7TaxFazkgLw1WA0/t1PfTL/kcHNDTfkSbfZN6CnohSBDLUqcZoppgP2bYmqovbbkYctpwpRUHIoy9QedLUfdP8UYKCaStsgtZNo8N2DjEKh73zQkFyHIfep4d5RIYHpR3tKgiDL+F3iQF2cm82p/yzIVm9XIhF79JSjjXLURS+ofcxtgdIoQTNOAMQmrbEB+I1V9OudEXVo4xEQ55743tTFc=
  strategy: git
