language: node_js

node_js:
  - 10.16.2

install:
    - npm install

cache: npm

# command to run tests
script:
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: "155046e8-2f0c-41d3-8483-8ca4265ce610"
