language: node_js

node_js:
- 10.16.2

install:
- npm install

cache: npm

script:
- npm test

services:
  - neo4j

env:
  - NEO_VERSION="2.1.2"

deploy:
  provider: heroku
  api_key:
    secure: olK5knVLlp5PW47ZIASbVFcJQYJxPT45USpO9R8pJyRRqZ2NGVsbAaQn/Dqm+06Ky9Nk5s97aYrDrUiIuhmwOFTlkZygCsI7B/UQPbrlX6wyS+Pf8D2cNIBX+Ss5jhrkzV5A9RRamPixzk10dUocAXmliUxwWxT1SUcsaI7VUt2R1IWKrgla1mnxQ4AQ9xf08sFfPpIbiWWnzyxrsXqgM9oUDY+yRhE9KB5ap11ZhvaTBesEeE0jN5wnxRb31aEstBm2+2ZkHkSMwi33w574b5w+ZAm0eLzJw0+SZtAyt0GPeds/Fs16GQfhc7CFkk3tronCn544GD6UsGvc9xyMdCy6odBDj0YYPzZd5lu7wOiOl9+U3SrWYuvu6ALz8u6YnI1kF0ADGLwnFdvXUi0vz40LttRxrJv5vwU/nsnW1vYYcnUmMlGdzLXz0DVYptLCy3p/fcIB5wWsWDayS45FMYNf6VUYI+sAwLZWvu4YWovUPrsaySVlpnxWB6Hzn0QdQccug/f8GnYJ286bNa9CveC0atn62CRogAoDWF9qEkU0xsB8EK7C8vNekaEzTjhSWq+yNLUhKZnwzJ3oYcCnsMPXoCdEDaye/U6fYAe5Ux1YSb9eXuWTnMnb26jmbAvDFAUHYpIlMu2SklzoHPJilDIusg0NV5YJXBvZYiwTd84=
  strategy: git
