language: node_js
node_js:
- 10.16.2
install:
- npm install
cache: npm
script:
- npm test
services:
- neo4j
env:
- NEO_VERSION="2.1.2"
deploy:
  provider: heroku
  api_key:
    secure: JXPSE2jO8MUkCvT8NjUO2I9sz71NpjihTBl10Jqloqlwos1xtoUDmiUmEAWJQqfTMH7mYC7Q/IqHc+pPeFzRFUcGrtNefeceorKCoa6erIogPIxABaUl7L5cCVJuL/YxFr269p1KtJi8fDangLUxZQn8P219gr9RfHHKluw8bTw2d6RDlzzZtKcLTcgsVF34yMAjmv82Wvpedwq45Gi70qtcXZB3jbUefR+rHTnCSWCD+lG2jANofd+eBT1K+VtbMD38z6HX9C8ITyiat6gE3Yzai8ARtz+Rthf3KArLWN1ZM5AJMvHqfqK/nAmEckEvEy9x/OSW5QNsUgOKUrDuqhyy1NbBnJeB15KxqidsBF/rfnMVLRB2sFgjeb5nWfXvl8uT/gpOH3ITydQymTFhkH1h7tey8WDx9YBw5anOv96ZSJNjyzgrWgyrnpDNY572yEG38nMtSjCtou5Aqp4vh//0PBwxQNT8wBx69mm7LQuq8NmH6kq8NlvVYBiO8DWKqpWUPmohC7u78CTnL0prg6vJGXizb1c5/TrszxgelULUuvAkmf3AMMNWUsW3ZNgWiR0bKWPjw1/+XKbejEmPmGcQleqq8e6uaGrfuQfcNpbWrynVcQVaniUeVwtYPC2aloy5E9+CsY0odgWCqbu7ZWHy+ymio2MCj9SNibKGEWk=
  app: GrafMuvi
  on:
    repo: lzontar/GrafMuvi
